let result = [{
  yiming: '金钱世界/万恶金钱(港)/世上所有的财富 ',
  pianming: 'All the Money in the World ',
  niandai: '2017 产　　地　美国 ',
  leibie: '剧情/犯罪/悬疑 ',
  yuyan: '英语 ',
  zimu: '中英双字幕 ',
  shangyingriqi: '2017-12-25(美国)/2018-03-02(中国) ',
  IMDbpingfen: '7.0/10 from 16,876 users ',
  doubanpingfen: '7.1/10 from 10,118 users ',
  wenjiangeshi: 'x264 + aac ',
  shipinchicun: '1280 x 720 ',
  wenjiandaxiao: '1CD ',
  pianchang: '132分钟 ',
  daoyan: '雷德利·斯科特 Ridley Scott ',
  zhuyan: '米歇尔·威廉姆斯 Michelle Williams 　　　　　　克里斯托弗·普卢默 Christopher Plummer 　　　　　　马克·沃尔伯格 Mark Wahlberg 　　　　　　查理·普拉默 Charlie Plummer 　　　　　　罗曼·杜里斯 Romain Duris 　　　　　　蒂莫西·赫顿 Timothy Hutton 　　　　　　斯塔西·马汀 Stacy Martin 　　　　　　查理·肖特韦尔 Charlie Shotwell 　　　　　　安德鲁·巴肯 Andrew Buchan 　　　　　　马克·莱昂纳蒂 Marco Leonardi 　　　　　　朱塞佩·博尼法蒂 Giuseppe Bonifati 　　　　　　尼可拉斯·瓦波里蒂斯 Nicolas Vaporidis 　　　　　　安德里亚·皮耶迪蒙特·博迪尼 Andrea Piedimonte Bodini 　　　　　　古列尔莫·法维拉 Guglielmo Favilla 　　　　　　尼古拉·迪奇欧 Nicola Di Chio 　　　　　　阿黛尔·蒂兰特 Adele Tirante 　　　　　　亚历山德拉·罗卡 Alessandra Roca 　　　　　　弗兰切斯卡·茵奥迪 Francesca Inaudi 　　　　　　丹尼尔·高斯林 Daniel Gosling 　　　　　　乔纳森·阿里斯 Jonathan Aris',
  jianjie: '　　电影《金钱世界》改编自一起曾轰动世界的豪门绑架事件：世界首富保罗·盖蒂（克里斯托弗·普卢默 饰）之孙遭遇黑帮绑架，绑匪向其母盖尔（米歇尔·威廉姆斯 饰）索要1700万美元赎金，已经与丈夫离婚的盖尔无力支付这笔高昂的赎金，只能向盖蒂家族求救，但富可敌国却无比吝啬的老盖蒂却拒绝为孙子（查理·普拉默 饰）支付赎金，拿不到钱的绑匪丧心病狂的割下了人质的耳朵邮寄给盖蒂家族，心碎的盖尔在前CIA特工弗莱彻·蔡斯（马克·沃尔伯格 饰）的协助下，试图撼动这一僵局，解救自己的儿子…… ',
  downloads: [],
  img: 'http://www.imageto.org/images/eUldT.jpg'
},
  {
    yiming: '达琳达/绝代天后黛莉达(台)',
    pianming: 'Dalida',
    niandai: '2017产　　地　法国',
    leibie: '传记',
    yuyan: '法语',
    shangyingriqi: '2017-01-11(法国)',
    IMDbpingfen: ' 6.9/10 from 1,447 usersIMDb链接  http://www.imdb.com/title/tt5039860/',
    doubanpingfen: '6.9/10 from 94 users豆瓣链接　https://movie.douban.com/subject/26770719/',
    pianchang: '124分钟',
    daoyan: '丽萨·阿祖洛斯 Lisa Azuelos',
    zhuyan: '文森特·佩雷斯 Vincent Perez里卡多·斯卡马里奥 Riccardo Scamarcio尼尔斯·施内德  Niels Schneider尼古拉斯·迪佛休尔 Nicolas Duvauchelle让-保罗·卢弗 Jean-Paul Rouve迈克尔·科恩 Micha?l CohenSveva AlvitiRoby Schinasi',
    jianjie: '★法国票房首周第二名★法国世纪之声，璀璨的歌坛传奇，★坐拥全球专辑销量一亿两千万张，荣获45座金唱片殊荣★当代潮流时尚指标，所到之处万人空巷，引爆欧洲歌迷疯狂热潮改编纵横歌坛30年，法国一代歌后黛莉达的传奇一生。出生于埃及开罗，黛莉达于1950年代开始歌唱生涯，以一曲《小女孩》(Bambino)红遍了整个巴黎和全法国，她独特的唱腔和美丽的风采更是席卷全欧洲。但在她光鲜亮丽的背后，却有着破碎的感情生活，爱人相继离开让她饱受无尽的悲痛，人生对她而言毫无希望，最后黛莉达选择服用安眠药自杀，留下的是她在人们心中独一无二的璀璨存在。',
    downloads: [],
    img: 'https://i.loli.net/2018/03/21/5ab26d2b59548.jpg'
  },
  undefined,
  {
    yiming: '马戏之王/大娱乐家(港/台)/地球最强秀/地球最强马戏演员/全球最伟大的马戏演员/大秀之王 ',
    pianming: 'The Greatest Showman ',
    niandai: '2017 产　　地　美国 ',
    leibie: '剧情/传记/歌舞 ',
    yuyan: '英语 ',
    zimu: '中英双字幕 ',
    shangyingriqi: '2017-12-20(美国)/2018-02-01(中国) ',
    IMDbpingfen: '7.9/10 from 83,447 users ',
    doubanpingfen: '7.9/10 from 61,447 users ',
    wenjiangeshi: 'x264 + aac ',
    shipinchicun: '1280 x 720 ',
    wenjiandaxiao: '1CD ',
    pianchang: '105分钟 ',
    daoyan: '迈克尔·格雷西 Michael Gracey ',
    zhuyan: '休·杰克曼 Hugh Jackman 　　　　　　米歇尔·威廉姆斯 Michelle Williams 　　　　　　扎克·埃夫隆 Zac Efron 　　　　　　赞达亚 Zendaya 　　　　　　丽贝卡·弗格森 Rebecca Ferguson 　　　　　　奥丝汀·约翰森 Austyn Johnson 　　　　　　卡梅伦·丝蕾 Cameron Seely 　　　　　　基拉·塞特尔 Keala Settle 　　　　　　萨姆·汉弗莱 Sam Humphrey 　　　　　　叶海亚·阿卜杜勒-迈丁 Yahya Abdul-Mateen II 　　　　　　埃里克·安德森 Eric Anderson 　　　　　　伊利斯·鲁宾 Ellis Rubin 　　　　　　斯凯勒·杜恩 Skylar Dunn 　　　　　　丹尼尔·埃维里奇 Daniel Everidge 　　　　　　拉杜·斯平格尔 Radu Spinghel 　　　　　　小森优作 Yusaku Komori 　　　　　　丹尼尔·松 Danial Son 　　　　　　保罗·斯帕克斯 Paul Sparks 　　　　　　威尔·斯文森 Will Swenson',
    jianjie: '　　《马戏之王》取材自真人真事，好莱坞全能巨星休·杰克曼在片中饰演“马戏团鼻祖”、传奇人物P.T.巴纳姆。故事讲述了身处社会底层的巴纳姆依靠自己无穷想象力和锲而不舍的精神，从经营博物馆到一手开创世界上第一家马戏团的故事。巴纳姆的奇思妙想最开始并不被大众所认可，几乎没人花钱欣赏，他的家人好友帮他度过一次次绝境。在经历了一系列挫折、与合作伙伴的分歧之后，秉持梦想的他终于成为全美甚至全世界最为知名的“造梦大师”。',
    downloads: [],
    img: 'http://www.imageto.org/images/jMxCo.jpg'
  },
  {
    yiming: '潜伏4：锁命亡灵/潜伏4/阴儿房第4章：锁命亡灵(台)/儿凶 第四回(港)/潜伏4：最后的线索/潜伏4：最后的钥匙 ',
    pianming: 'Insidious: The Last Key ',
    niandai: '2018 产　　地　美国/加拿大 ',
    leibie: '惊悚/恐怖 ',
    yuyan: '英语 ',
    zimu: '中英双字幕 ',
    shangyingriqi: '2018-01-05(美国) ',
    IMDbpingfen: '5.8/10 from 13,394 users ',
    doubanpingfen: '5.8/10 from 773 users ',
    wenjiangeshi: 'x264 + aac ',
    shipinchicun: '1280 x 720 ',
    wenjiandaxiao: '1CD ',
    pianchang: '103分钟 ',
    daoyan: '亚当·罗比特尔 Adam Robitel ',
    zhuyan: '林·沙烨 Lin Shaye 　　　　　　雷·沃纳尔 Leigh Whannell 　　　　　　安格斯·桑普森 Angus Sampson 　　　　　　柯克·埃斯沃多 Kirk Acevedo 　　　　　　凯特琳·杰拉德 Caitlin Gerard 　　　　　　史宾塞·洛克 Spencer Locke 　　　　　　乔什·斯图沃特 Josh Stewart 　　　　　　特莎·费勒 Tessa Ferrer 　　　　　　阿勒奎·里德 Aleque Reid 　　　　　　阿瓦·科尔克 Ava Kolker 　　　　　　皮尔斯·波普 Pierce Pope 　　　　　　布鲁斯·戴维森 Bruce Davison 　　　　　　哈维尔·博泰特 Javier Botet 　　　　　　马库斯·亨德森 Marcus Henderson 　　　　　　阿曼达·亚罗斯 Amanda Jaros',
    jianjie: '　　《阴儿房第3章：从灵开始》琳雪伊回归饰演超自然心理学家，由《失魂记忆》导演亚当罗勃提尔执导、《阴儿房》系列原创团队之一的雷沃纳尔执笔剧本、鬼才导演温子仁将担任制片，打造极致惊悚的最新经典。',
    downloads: [],
    img: 'http://www.imageto.org/images/oj08.jpg'
  },
  {
    yiming: '交响班',
    pianming: 'La mélodie',
    niandai: '2017产　　地　法国',
    leibie: '剧情/喜剧',
    yuyan: '法语',
    shangyingriqi: '2017-09-02(威尼斯电影节)/2017-11-08(法国)',
    IMDbpingfen: '6.7/10 from 132 usersIMDb链接 http://www.imdb.com/title/tt1633217/',
    doubanpingfen: '7.0/10 from 13 users豆瓣链接　https://movie.douban.com/subject/5153600/',
    pianchang: '102分钟',
    daoyan: 'Rachid Hami',
    zhuyan: '凯德·麦拉德 Kad Merad　　　　　　萨米尔·盖丝米 Samir Guesmi　　　　　　科琳娜·马尔尚 Corinne Marchand',
    jianjie: '将满50岁的西蒙是一名杰出的小提琴家，他看破一切，对世事不抱任何幻想。因缘际会之下，西蒙来到巴黎一所初级中学，教导六年级学生演奏小提琴，但其严谨的教学方式，让他难以和顽皮捣蛋的孩子们建立关系，为此吃尽苦头。教室裡一位异常害羞的男孩阿诺，对小提琴深感著迷，西蒙被阿诺的天赋深深打动，在班上的欢乐气氛感染之下，也渐渐重拾音乐带来的快乐。身为菜鸟教师的西蒙，能有足够毅力克服重重障碍、并实现带领孩子登上巴黎爱乐厅的承诺吗？　　本片创作契机源于法国巴黎爱乐厅的「Démos管弦乐教育计画」，在贫困社区中创设儿童管弦乐团，透过实作带领8-12岁学童探索音乐。导演哈希德阿米（Rachid Hami）跟随计画团队拍摄纪录片的过程中，逐渐与孩子们建立连结，主角阿诺的故事也于脑中成形。《放牛班的提琴手》每位孩子都是巴黎当地素人演员，他们演出的不仅是角色，更是最真实的生命写照，当面对贫穷、暴力、或被遗弃的无助感时，仍拥有追求理想与希望的信念。',
    downloads: [],
    img: 'http://202.102.26.253:8182/files/138/Q1ng/p2498527626.jpg'
  },
  undefined,
  undefined,
  {
    yiming: 'Cross-DimensionLove',
    pianming: '跨次元少女大作战',
    niandai: '2018产　　地　中国大陆',
    leibie: '剧情/喜剧/爱情',
    yuyan: '汉语普通话',
    zimu: '中文字幕',
    shangyingriqi: '2018-03-16(中国大陆)',
    wenjiangeshi: 'x264 + ACC',
    shipinchicun: '1280 x 720',
    wenjiandaxiao: '1485 MB',
    pianchang: '95 Mins',
    daoyan: '吴立素 Lisu Wu',
    zhuyan: '黄礼格 Lige Huang　　　　　　贺盼盼 Panpan He　　　　　　张舸 Ge Zhang　　　　　　叶幸运 Xingyun Ye　　　　　　陈炳林 Bing-Lam Chan',
    jianjie: '大龄待嫁网络漫画作家暖暖是一名迷迷糊糊的女青年。她常常一个人天马行空，活在自己构建的小世界里，与自己笔下的漫画人物李豆豆突破次元壁建立了一段深厚情谊。暖暖超龄未婚成为家人心头大石，家人决意明修栈道，暗渡陈仓，装病催婚，致使暖暖卷入了一段令人嘀笑皆非的相亲之旅。在酒屋老板小沫、鼓手小欧、贝斯手小布的陪伴下暖暖过五关斩六将与不靠谱相亲对象斗智斗勇。 　　虽然过程艰难，但纸片人李豆豆永远无条件支持暖暖，鼓励她，逗她开心。暖暖也渐渐对李豆豆产生了深深的依恋，可事态渐渐失控，相亲男Tony成功搞定暖暖的父母，暖暖在家庭与社会的压力下逐渐迷失了自己。盼盼到底会不会答应Tony的追求，而她和李豆豆的感情又该何去何从，毕竟在现实生活中很难获得漫画中的李豆豆那样无微不至的完美恋人……',
    downloads: [],
    img: 'http://www.seehd.so/attachment/thumb/1803/thread/2_144132_589a60165e534d9.jpg'
  },
  {
    yiming: '勇敢者游戏：决战丛林/野蛮游戏：疯狂丛林(台)',
    pianming: 'Jumanji: Welcome to the Jungle',
    niandai: '2017产　　地　美国',
    leibie: '动作/奇幻/冒险',
    yuyan: '国语',
    shangyingriqi: '2017-12-20(美国)/2018-01-12(中国大陆)',
    doubanpingfen: '7.5/10 from 1,457 users',
    pianchang: '111分钟',
    daoyan: '杰克·卡斯丹 Jake Kasdan',
    zhuyan: '道恩·强森 Dwayne Johnson　　　　　　凯文·哈特 Kevin Hart　　　　　　杰克·布莱克 Jack Black　　　　　　凯伦·吉兰 Karen Gillan　　　　　　尼克·乔纳斯 Nick Jonas　　　　　　瑞斯·达比 Rhys Darby　　　　　　鲍比·坎纳瓦尔 Bobby Cannavale　　　　　　亚历克斯·沃尔夫 Alex Wolff　　　　　　瑟达吕斯·布兰 Ser\'Darius Blain　　　　　　麦迪森·伊瑟曼 Madison Iseman　　　　　　摩根·特纳 Morgan Turner　　　　　　梅森·古乔内 Mason Guccione　　　　　　马克·埃文·杰克逊 Marc Evan Jackson　　　　　　玛琳·辛科 Marin Hinkle　　　　　　特雷西·邦纳 Tracey Bonner　　　　　　玛莉贝丝·梦露 Maribeth Monroe　　　　　　米西·派勒 Missi Pyle　　　　　　杰米·雷内尔 Jamie Renell　　　　　　卡尔利斯·布克 Carlease Burke　　　　　　罗翰·昌德 Rohan Chand　　　　　　科林·汉克斯 Colin Hanks',
    jianjie: '　　《勇敢者游戏：决战丛林》讲述了四名性格迥异的高中生意外穿越到险象环生的勇敢者游戏中，变身成为与自身性格外貌截然不同的游戏角色。面对丛林猛兽的袭击和邪恶势力的追捕，四人必须在冒险家（道恩·强森 Dwayne Johnson 饰）的带领下，战胜重重危机，赢得游戏，才能获得重返现实的机会的故事。',
    downloads: [],
    img: 'http://n.sinaimg.cn/ent/transform/w630h933/20171222/o111-fypvuqf1838418.jpg'
  },
  {
    yiming: '湮灭/灭绝(台)/灭。境(港)/遗落的南境1：湮灭 ',
    pianming: 'Annihilation ',
    niandai: '2018 产　　地　美国/英国 ',
    leibie: '科幻/悬疑/惊悚 ',
    yuyan: '英语 ',
    zimu: '中英双字幕 ',
    shangyingriqi: '2018-02-23(美国) ',
    IMDbpingfen: '7.8/10 from 14,359 users ',
    doubanpingfen: '7.9/10 from 1,757 users ',
    wenjiangeshi: 'x264 + aac ',
    shipinchicun: '1280 x 720 ',
    wenjiandaxiao: '1CD ',
    pianchang: '115分钟 ',
    daoyan: '亚历克斯·加兰 Alex Garland ',
    zhuyan: '娜塔莉·波特曼 Natalie Portman 　　　　　　詹妮弗·杰森·李 Jennifer Jason Leigh 　　　　　　奥斯卡·伊萨克 Oscar Isaac 　　　　　　吉娜·罗德里格兹 Gina Rodriguez 　　　　　　泰莎·汤普森 Tessa Thompson 　　　　　　水野索诺娅 Sonoya Mizuno 　　　　　　大卫·吉雅西 David Gyasi 　　　　　　图娃·诺沃妮 Tuva Novotny 　　　　　　本尼迪克特·王 Benedict Wong 　　　　　　约翰·施瓦布 John Schwab 　　　　　　萨米·海曼 Sammy Hayman 　　　　　　乔希·丹福德 Josh Danford 　　　　　　克里斯汀·麦加里蒂 Kristen McGarrity',
    jianjie: '　　生物学家Lena(波特曼)为调查丈夫(伊萨克饰)的失踪，参加了神秘组织Southern Reach组织的科学考察，4名女性组队，去研究美国领土内一块被检疫隔离的生态灾害区域“X地区”。她发现那里是原生态的荒野，隐藏着神秘的黑暗力量。这已经是对该地区的第12次考察，前11次全都 失败，比如第二次考察终结于去的考察队员集体自杀，第三次考察队拔枪互相残杀，第11次队员全体失去神志，回来后不久都死于癌症……  ',
    downloads: [],
    img: 'http://www.imageto.org/images/x06jJ.jpg'
  },
  {
    yiming: '九三年夏天/夏日1993/九三年之夏/那年夏天，阳光灿烂(港) ',
    pianming: 'Estiu 1993 ',
    niandai: '2017 产　　地　西班牙 ',
    leibie: '剧情/家庭 ',
    yuyan: '加泰罗尼亚语 ',
    zimu: '中文 ',
    IMDbpingfen: '7.2/10 from 2,070 users ',
    doubanpingfen: '7.9/10 from 1,616 users ',
    wenjiangeshi: 'x264 + aac ',
    shipinchicun: '1280 x 692 ',
    wenjiandaxiao: '1CD ',
    pianchang: '97分钟 ',
    daoyan: '卡拉·西蒙·皮坡 Carla Simon Pipó ',
    zhuyan: '布鲁娜·库希 Bruna Cusí 　　　　　　莱娅·阿蒂加斯 Laia Artigas 　　　　　　保拉·罗伯斯 Paula Robles 　　　　　　大卫·贝尔达格尔 David Verdaguer 　　　　　　费米·雷克萨奇 Fermí Reixach 　　　　　　蒙特赛·桑斯 Montse Sanz 　　　　　　伊莎贝尔·罗卡蒂 Isabel Rocatti 　　　　　　贝尔塔·皮坡 Berta Pipó 　　　　　　埃特纳·坎皮略 Etna Campillo 　　　　　　宝拉·布兰科 Paula Blanco 　　　　　　詹迪·菲格拉斯 Jordi Figueras',
    jianjie: '　　导演的自传性叙事。用细致温柔的镜头跟随一个小孩子在夏天失去母亲，来到新家庭，如何进入别人家庭的故事，虽是悲剧，但处理得很轻。影调略平淡闲散，但由于聚焦在孩子身上，导演细心地抓到了不少童真童趣瞬间，孩童时代西班牙夏天的缓慢时光也颇有韵味，整部影片温情柔软，成人世界的苦恼只是短暂的出现，但儿童的世界也不是只有无忧无虑，在观影过程中我们也深深感受到主人公小女孩失去母亲的迷茫和悲痛，并伴随着她逐渐治愈，并且接受新家庭，学习被新家庭接受的过程。影片入围2017年柏林电影节“新生代”单元，并获得最佳处女作奖。',
    downloads: [],
    img: 'http://www.imageto.org/images/qCYOS.jpg'
  },
  {
    yiming: '天上再见 ',
    pianming: 'Au revoir la-haut/See You Up There ',
    niandai: '2017 产　　地　法国/加拿大 ',
    leibie: '剧情/战争 ',
    yuyan: '法语 ',
    shangyingriqi: '2017-10-25(法国) ',
    IMDbpingfen: '7.7/10 from 1,757 users ',
    doubanpingfen: '7.9/10 from 583 users ',
    wenjiangeshi: 'x264 + aac ',
    shipinchicun: '1280 x 720 ',
    wenjiandaxiao: '1CD ',
    pianchang: '117分钟 ',
    daoyan: '艾尔伯特·杜邦迪 Albert Dupontel ',
    zhuyan: '纳威尔·佩雷兹·毕斯卡亚特 Nahuel Pérez Biscayart 　　　　　　阿尔贝·杜邦泰尔 Albert Dupontel 　　　　　　罗兰·拉斐特 Laurent Lafitte 　　　　　　尼尔斯·阿雷斯特吕普 Niels Arestrup 　　　　　　艾米莉·德奎恩 émilie Dequenne 　　　　　　梅兰尼·蒂埃里 Mélanie Thierry 　　　　　　埃洛伊兹·巴尔斯特 Hélo?se Balster 　　　　　　菲利普·乌禅 Philippe Uchan 　　　　　　安德烈·马尔孔 André Marcon 　　　　　　米歇尔·维耶尔莫 Michel Vuillermoz 　　　　　　凯恩·科贾迪 Kyan Khojandi 　　　　　　菲利普·杜克斯纳 Philippe Duquesne',
    jianjie: '　　演而优则导的法国演技派男星亚伯杜庞蒂自导自演的《天上再见》，改编自犯罪小说大师皮耶勒梅特的同名小说，讲述两名因目睹长官犯罪而惨遭惩处的军人，没想到退役后长官飞黄腾达，自己却一贫如洗，为不让小人得志，他们决定要为自己讨回公道。影片精采刻画第一次世界大战过后法国社会，从血肉横飞的泥泞战场到纸醉金迷的华美派对，但即便面具绚丽华美，也掩盖不住背后的人生伤痛。',
    downloads: [],
    img: 'http://www.imageto.org/images/ciN0L.jpg'
  },
  {
    yiming: '局外人/外来者',
    pianming: 'The Outsider',
    niandai: '2018产　　地　美国',
    leibie: '动作/犯罪/惊悚',
    shangyingriqi: '2018-03-09(美国)',
    IMDbpingfen: ' 7.5/10 from 11 usersIMDb链接  http://www.imdb.com/title/tt2011311/帖子整理http://www.btbtt.co',
    daoyan: '马丁·赞里维特 Martin Zandvliet',
    zhuyan: '杰瑞德·莱托 Jared Leto浅野忠信 Tadanobu Asano椎名桔平 Kippei Shiina忽那汐里 Kutsuna Shiori罗利·科奇瑞恩 Rory Cochrane埃米尔·赫施 Emile Hirsch大森南朋 Nao Omori田中泯 Min Tanaka',
    jianjie: '一名在战后日本被囚禁的美国士兵，进入极道的阴暗世界，融入他们的生态以偿还自由。',
    downloads: [],
    img: 'http://www.btbtt.co/upload/attach/004/315/d63509525a54bb8f695f153b66a7eb7c.jpg'
  },
  {
    yiming: '星球大战8：最后的绝地武士/星球大战：最后绝地武士(港)',
    pianming: 'Star Wars: The Last Jedi',
    niandai: '2017产　　地　美国',
    leibie: '动作/科幻/冒险',
    yuyan: '英语',
    zimu: '中英双字',
    shangyingriqi: '2017-12-15(美国)/2018-01-05(中国大陆)',
    doubanpingfen: '7.5/10 from 4,067 users',
    pianchang: '152分钟',
    daoyan: '莱恩·约翰逊 Rian Johnson',
    zhuyan: '黛西·雷德利 Daisy Ridley约翰·博耶加 John Boyega亚当·德赖弗 Adam Driver马克·哈米尔 Mark Hamill凯丽·费雪 Carrie Fisher奥斯卡·伊萨克 Oscar Isaac安迪·瑟金斯 Andy Serkis多姆纳尔·格里森 Domhnall Gleeson露皮塔·尼永奥 Lupita Nyong\'o格温多兰·克里斯蒂 Gwendoline Christie凯莉·玛丽·陈 Kelly Marie Tran劳拉·邓恩 Laura Dern本尼西奥·德尔·托罗 Benicio Del Toro安东尼·丹尼尔斯 Anthony Daniels吉米·维 Jimmy Vee比莉·洛德 Billie Lourd沃维克·戴维斯 Warwick Davis赫敏·科菲尔德 Hermione Corfield马克·路易斯·琼斯 Mark Lewis Jones伊川东吾 Togo Igawa阿克谢·库玛尔 Akshay Kumar克里斯塔·克拉克 Crystal Clarke约瑟夫·高登-莱维特 Joseph Gordon-Levitt',
    jianjie: '　　《星球大战8》（Star Wars: Episode VIII）是动作、科幻、冒险电影《星球大战后传》系列的第2部，由莱恩·约翰逊执导，黛茜·雷德利、约翰·波耶加、格温多兰·克里斯蒂、奥斯卡·伊萨克联合主演。影片故事紧接《星球大战：原力觉醒》，讲述了遥远的银河系中恐怖政权“第一秩序”袭击新共和国首都之后的事。',
    downloads: [],
    img: 'http://himg2.huanqiu.com/attachment2010/2017/1228/20171228111938360.jpg'
  },
  {
    yiming: 'HandlewithCare',
    pianming: 'Hjertestart',
    niandai: '2017产　　地　挪威',
    leibie: '剧情',
    yuyan: '挪威语/英语/西班牙语',
    shangyingriqi: '2017-02-24(挪威)',
    IMDbpingfen: ' 6.9/10 from 112 usersIMDb链接  http://www.imdb.com/title/tt4880630/',
    doubanpingfen: '0/10 from 5 users豆瓣链接　https://movie.douban.com/subject/26992432/',
    pianchang: '102分钟（挪威）',
    daoyan: 'Arild Andresen',
    zhuyan: 'Marlon MorenoKristoffer JonerPatricia CastañedaAmalia Santamaria',
    jianjie: '杰提是挪威海岸线的钻油台工人，中年突逢妻子意外身亡，迫使他必须得单独照顾他们共同领养的小男孩丹尼尔。过去仰赖亡妻积习成惯，使杰提作为单亲爸爸的过程备受波折；在无法承担父职压力下，杰提决定带着丹尼尔，回到小男孩的原生地，南美洲的哥伦比亚，去寻找他的原生母亲。父子二人，在当地一位计程车问将的协助下，展开一段有笑有泪，出乎意料的温情寻根之旅。',
    downloads: [],
    img: 'http://202.102.26.253:8182/files/138/Q1ng/p2443825008.jpg'
  },
  {
    yiming: '冰肤传说/冷皮',
    pianming: 'Cold Skin',
    niandai: '2017产　　地　西班牙/法国',
    leibie: '剧情/科幻/惊悚',
    yuyan: '英语',
    shangyingriqi: '2017(法国)',
    IMDbpingfen: ' 5.8/10 from 895 usersIMDb链接  http://www.imdb.com/title/tt1034385/',
    doubanpingfen: '6.9/10 from 10 users豆瓣链接　https://movie.douban.com/subject/3148967/',
    pianchang: '107m',
    daoyan: '泽维尔·吉恩斯 Xavier Gens',
    zhuyan: '大卫·奥克斯 David Oakes雷·史蒂文森 Ray Stevenson奥拉·加里多 Aura Garrido',
    jianjie: '1914年第一次世界大战前夕，一名气象学家被派往南极孤岛上做气候观测。然而他很快发现，岛上除了他和一个疯疯癫癫的灯塔员，还有其它生物的存在... 影片改编自同名小说。',
    downloads: [],
    img: 'http://www.btbtt.co/upload/attach/004/275/e3e43a2c08ce449418871e7601c5b789.jpg'
  },
  undefined,
  {
    yiming: '缩小人生/缩身 ',
    pianming: 'Downsizing ',
    niandai: '2017 产　　地　美国 ',
    leibie: '剧情/喜剧/科幻 ',
    yuyan: '英语 ',
    zimu: '中英双字幕 ',
    shangyingriqi: '2017-08-30(威尼斯电影节)/2017-12-22(美国) ',
    IMDbpingfen: '5.7/10 from 18,916 users ',
    doubanpingfen: '5.4/10 from 830 users ',
    wenjiangeshi: 'RMVB + aac ',
    shipinchicun: '1280 x 720 ',
    wenjiandaxiao: '1CD ',
    pianchang: '135分钟 ',
    daoyan: '亚历山大·佩恩 Alexander Payne ',
    zhuyan: '马特·达蒙 Matt Damon 　　　　　　克里斯托弗·沃尔兹 Christoph Waltz 　　　　　　周洪 Hong Chau 　　　　　　克里斯汀·韦格 Kristen Wiig 　　　　　　罗夫·拉斯加德 Rolf Lassgard 　　　　　　英洁德·埃格伯格 Ingjerd Egeberg 　　　　　　乌多·基尔 Udo Kier 　　　　　　索伦·比尔马克 Soren Pilmark 　　　　　　杰妮·霍蒂谢尔 Jayne Houdyshell 　　　　　　杰森·苏戴奇斯 Jason Sudeikis 　　　　　　玛莉贝丝·梦露 Maribeth Monroe 　　　　　　菲尔·里夫斯 Phil Reeves 　　　　　　布里盖特·伦迪·佩恩 Brigette Lundy-Paine 　　　　　　詹姆斯·范德比克 James Van Der Beek 　　　　　　艾丽森·J·帕尔默 Alison J. Palmer 　　　　　　蒂姆·德里斯科尔 Tim Driscoll 　　　　　　凯文·孔克尔 Kevin Kunkel 　　　　　　派崔克·盖勒 Patrick Gallagher 　　　　　　安娜·玛丽·考克斯 Ana Marie Cox 　　　　　　罗兰·马丁 Roland Martin 　　　　　　尼尔·帕特里克·哈里斯 Neil Patrick Harris 　　　　　　劳拉·邓恩 Laura Dern 　　　　　　南希·纳什 Niecy Nash 　　　　　　玛格·马丁戴尔 Margo Martindale 　　　　　　凯瑞·肯妮 Kerri Kenney 　　　　　　唐·雷克 Don Lake 　　　　　　玛丽·凯·普莱斯 Mary Kay Place',
    jianjie: '　　在《缩身》中，亚历山大·佩恩描写了一对财政紧张的夫妇，为了节省开支他们决定“缩身”——把自己变得更小，这样日常消耗也就少多了。然而在缩身开始前的最后一秒，妻子退怯了，只有丈夫进行了缩身。由此带来的结果是，迷你小丈夫（马特·戴蒙）与妻子在很多方面开始出现不和谐，夫妻关系陷入紧张。 ',
    downloads: [],
    img: 'http://www.imageto.org/images/4xrWD.jpg'
  },
  undefined]